### ISSUE TITLE
Failure to load texture coordinates

### ISSUE THREAD

**Issue by spapapan** [andresoviedo/android-3D-model-viewer#59]
Hello, 

I am trying to open an OBJ with texture but I get this error:

```

E/Object3DBuilder: Failure to load texture coordinates
                                                                             java.lang.IndexOutOfBoundsException: index=-2 out of bounds (limit=4330)
                                                                                 at java.nio.Buffer.checkIndex(Buffer.java:528)
                                                                                 at java.nio.ByteBufferAsFloatBuffer.get(ByteBufferAsFloatBuffer.java:95)
                                                                                 at org.andresoviedo.app.model3D.model.Object3DBuilder.generateArrays(Object3DBuilder.java:663)
                                                                                 at org.andresoviedo.app.model3D.model.Object3DBuilder.loadV5(Object3DBuilder.java:411)
                                                                                 at org.andresoviedo.app.model3D.services.ExampleSceneLoader$1.doInBackground(ExampleSceneLoader.java:82)
                                                                                 at org.andresoviedo.app.model3D.services.ExampleSceneLoader$1.doInBackground(ExampleSceneLoader.java:38)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                 at java.lang.Thread.run(Thread.java:762)
```

How can I solve this?

**Comment by andresoviedo** [comment]
Please try latest version. It should be fixed. If it doesn't, please reopen issue.

**Comment by spapapan** [comment]
I cloned the project and opened it with android studio. Where is the latest version?

**Comment by spapapan** [comment]
https://files.fm/u/v988pk4w

**Comment by andresoviedo** [comment]
I loaded your model succesfully.  I can see a gun with textures.  However, I don't see that message "objname.mtl:null".  What I'have seen is that your obj points to TESTMOLOS.mtl  (in uppercase) and file is actually testmolos.mtl (in lowercase).  However, in my phone it works still like that with no error message.
If you want you can try to match the filename case and see what happens.
If you still have problems it would be fine to have the logcat to check further the issue.

**Comment by spapapan** [comment]
I renamed the file but I still have the same issue. Here is an error that occurs when I load the file:

```
09-28 12:23:11.987 26094-27018/org.andresoviedo.dddmodel2 I/Object3DBuilder: Reading materials...
09-28 12:23:11.988 26094-27018/org.andresoviedo.dddmodel2 W/ContentUtils: Media not found: TESTMOLOS.mtl
    Available media: {cowboy.png=assets://assets/models/cowboy.png, ToyPlane.bmp=assets://assets/models/ToyPlane.bmp, wolf.stl=assets://assets/models/wolf.stl, penguin.bmp=assets://assets/models/penguin.bmp, cube.bmp=assets://assets/models/cube.bmp, ToyPlane.mtl=assets://assets/models/ToyPlane.mtl, penguin.mtl=assets://assets/models/penguin.mtl, ship.mtl=assets://assets/models/ship.mtl, ToyPlane.obj=assets://assets/models/ToyPlane.obj, triangle.obj=assets://assets/models/triangle.obj, cowboy.dae=assets://assets/models/cowboy.dae, TESTMOLOS.obj=assets://assets/models/TESTMOLOS.obj, teapot.obj=assets://assets/models/teapot.obj, ship.png=assets://assets/models/ship.png, cube.obj=assets://assets/models/cube.obj, penguin.obj=assets://assets/models/penguin.obj, cube.mtl=assets://assets/models/cube.mtl, TESTMOLOS=assets://assets/models/TESTMOLOS, ship.obj=assets://assets/models/ship.obj, ship.bmp=assets://assets/models/ship.bmp}
09-28 12:23:11.988 26094-27018/org.andresoviedo.dddmodel2 E/Object3DBuilder: Couldn't load material file TESTMOLOS.mtl. null
    java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at org.andresoviedo.android_3d_model_engine.services.Object3DBuilder.generateArrays(Object3DBuilder.java:479)
        at org.andresoviedo.android_3d_model_engine.services.wavefront.WavefrontLoaderTask.build(WavefrontLoaderTask.java:78)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:60)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

**Comment by andresoviedo** [comment]
Hey,

Please be sure you have put correctly "TESTMOLOS.mtl" in the "assets/models"  folder.
The log says there is no TESTMOLOS.mtl in that folder. Check the log saying  "Available media ..."
By the way, did you see you have a "TESTMOLOS" file that have no extension?  Is it your mtl file?

Regards
